-- Create Enum Types (Execute this block ONCE. If types exist, ignore error or drop them first)
DO $$ BEGIN
    CREATE TYPE location_type AS ENUM ('WAREHOUSE', 'STORE');
    CREATE TYPE user_role AS ENUM ('ADMIN', 'MANAGER', 'CASHIER');
    CREATE TYPE transaction_type AS ENUM ('PURCHASE', 'SALE', 'TRANSFER_OUT', 'TRANSFER_IN');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- Create Tables
CREATE TABLE IF NOT EXISTS locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  type location_type NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Seed Locations (Only if empty)
INSERT INTO locations (name, type)
SELECT 'Central Godown', 'WAREHOUSE'
WHERE NOT EXISTS (SELECT 1 FROM locations);

INSERT INTO locations (name, type)
SELECT 'Shop 1 - Downtown', 'STORE'
WHERE NOT EXISTS (SELECT 1 FROM locations WHERE name = 'Shop 1 - Downtown');

INSERT INTO locations (name, type)
SELECT 'Shop 2 - Mall', 'STORE'
WHERE NOT EXISTS (SELECT 1 FROM locations WHERE name = 'Shop 2 - Mall');

INSERT INTO locations (name, type)
SELECT 'Shop 3 - Suburbs', 'STORE'
WHERE NOT EXISTS (SELECT 1 FROM locations WHERE name = 'Shop 3 - Suburbs');

CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sku TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  description TEXT,
  price DECIMAL(10,2) NOT NULL DEFAULT 0,
  cost_price DECIMAL(10,2) NOT NULL DEFAULT 0,
  category TEXT,
  min_stock_alert INT NOT NULL DEFAULT 10,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS inventory (
  product_id BIGINT REFERENCES products(id) ON DELETE CASCADE,
  location_id BIGINT REFERENCES locations(id) ON DELETE CASCADE,
  quantity INT NOT NULL DEFAULT 0,
  PRIMARY KEY (product_id, location_id)
);

CREATE TABLE IF NOT EXISTS transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type transaction_type NOT NULL,
  product_id BIGINT REFERENCES products(id),
  from_location_id BIGINT REFERENCES locations(id),
  to_location_id BIGINT REFERENCES locations(id),
  quantity INT NOT NULL,
  status TEXT DEFAULT 'COMPLETED', -- Added this upfront to avoid migration issues later
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users(id) PRIMARY KEY,
  role user_role DEFAULT 'CASHIER',
  assigned_location_id BIGINT REFERENCES locations(id),
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS (Row Level Security)
ALTER TABLE locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory ENABLE ROW LEVEL SECURITY;
ALTER TABLE transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- DROP EXISTING POLICIES TO AVOID CONFLICT
DROP POLICY IF EXISTS "Public read locations" ON locations;
DROP POLICY IF EXISTS "Public read products" ON products;
DROP POLICY IF EXISTS "Public insert products" ON products;
DROP POLICY IF EXISTS "Public update products" ON products;
DROP POLICY IF EXISTS "Public read inventory" ON inventory;
DROP POLICY IF EXISTS "Public all inventory" ON inventory;
DROP POLICY IF EXISTS "Public read transactions" ON transactions;
DROP POLICY IF EXISTS "Public insert transactions" ON transactions;
DROP POLICY IF EXISTS "Public update transactions" ON transactions;
DROP POLICY IF EXISTS "Read own profile" ON profiles;
DROP POLICY IF EXISTS "Read all profiles" ON profiles;

-- POLICIES FIXED
CREATE POLICY "Public read locations" ON locations FOR SELECT USING (auth.role() = 'authenticated');

CREATE POLICY "Public read products" ON products FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Public insert products" ON products FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Public update products" ON products FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Public read inventory" ON inventory FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Public all inventory" ON inventory FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Public read transactions" ON transactions FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Public insert transactions" ON transactions FOR INSERT WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Public update transactions" ON transactions FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Read own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Read all profiles" ON profiles FOR SELECT USING (auth.role() = 'authenticated');
